apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: carshop
type: Opaque
stringData:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydb
  DATABASE_URL: postgres://myuser:mypassword@db-psql.carshop.svc.cluster.local:5432/mydb
